# This is a basic workflow to help you get started with Actions

name: CI to GitHubPage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Use Node.js 10.x
       uses: actions/setup-node@v1
       with:
         node-version: 10.x

     - name: Prepare and deploy
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         npm install
         npm run ng -- deploy --base-href=/CheckersGame/ --name="AutoDeploy" --email=bot@bot.com
